// Builds the market source tree from the main source tree.
//
//   node tools/build-market.cjs
//
// - market/source/index.html  <- source/index.html (verbatim)
// - market/source/style.css   <- source/style.css  (verbatim)
// - market/source/ui.js       <- market/lx-module.js + source/ui.js
// - market/source/worker.js   <- already committed (empty module, market rule)
//
// The lx-module wraps itself in an IIFE so its `const app` cannot collide
// with the ui.js top-level `const app`. Run after every ui.js/index.html/
// style.css change; commit the generated files so the market tree stays
// self-contained for submission.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = path.join(root, 'market', 'source');

fs.mkdirSync(out, { recursive: true });

const copy = (src, dst) => {
  fs.copyFileSync(path.join(root, src), path.join(out, dst));
  console.log(`copied ${src} -> market/source/${dst}`);
};

copy('source/index.html', 'index.html');
copy('source/style.css', 'style.css');

const lx = fs.readFileSync(path.join(root, 'market', 'lx-module.js'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'source', 'ui.js'), 'utf8');
const banner = '// Generated by tools/build-market.cjs — do not edit by hand.\n';
fs.writeFileSync(path.join(out, 'ui.js'), `${banner}\n${lx.trim()}\n\n${ui}`);
console.log('generated market/source/ui.js (lx-module + source/ui.js)');

if (fs.existsSync(path.join(root, 'source', 'worker.js'))) {
  console.log('note: market/source/worker.js is intentionally empty; not copied from source/worker.js');
}
